name: "Update readme image"

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"


jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run script
        run: |
            cd ./src
            go run main.go
  
      - name: Setup git config
        run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"

      - name: Commit the file
        run: |
          git add ./repo/profilehash.png
          git commit -m "🤖 update image"
          git push origin main
